### ISSUE TITLE
Want to add this project to LGUCC?

### ISSUE THREAD

**Issue by Zain-ul-din** [Ahmad-Murtaza2/ChatBox-with-Client-Server-Architecture#1]
[LGUCC](https://github.com/LGUCC) is a open-source LGU code community. If you'd like your project to be featured among the LGUCC projects, please include setup instructions for the repository in the readme.md file. Once that's done, let me know and I'll fork it.

**Comment by Ahmad-Murtaza2** [comment]
kindly explain me I can’t understand

**Comment by Zain-ul-din** [comment]
![image](https://github.com/Ahmad-Murtaza2/ChatBox-with-Client-Server-Architecture/assets/78583049/8cfb1c46-09a3-4f97-b746-674564ed667b)
